import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TextHoverEffect } from "@/components/ui/text-hover-effect";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
            >
                {children}
                <footer className="h-[40rem] flex flex-col items-center justify-center">
                    <TextHoverEffect text="MONC." />
                    <p className="text-center text-gray-500 mb-4">Made with ❤️ by Monc</p>
                </footer>
            </body>
        </html>
    );
}
